language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install qt5-default

install: 
  - git clone https://github.com/sailfishos/libsailfishapp dependencies/libsailfishapp
  - cd dependencies/libsailfishapp
  - git checkout tags/0.0.6 -b 0.0.6
  - qmake PREFIX=/usr .
  - make
  - sudo make install
  - cd ../..

script:
  - qmake
  - make

notifications:
  email: false
