language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install qt5-default qtdeclarative5-dev

install: 
  - git clone https://github.com/sailfishos/libsailfishapp dependencies/libsailfishapp
  - cd dependencies/libsailfishapp
  - git checkout tags/1.0.2 -b 1.0.2
  - qmake PREFIX=/usr .
  - make
  - sudo make install
  - cd ../..

script:
  - qmake
  - make

notifications:
  email: false
